// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: test_service.proto

package testpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testproto "github.com/o3co/protobuf.interceptors/testproto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestServiceName is the fully-qualified name of the TestService service.
	TestServiceName = "test.v1.TestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestServiceGetResourceProcedure is the fully-qualified name of the TestService's GetResource RPC.
	TestServiceGetResourceProcedure = "/test.v1.TestService/GetResource"
	// TestServiceCreateResourceProcedure is the fully-qualified name of the TestService's
	// CreateResource RPC.
	TestServiceCreateResourceProcedure = "/test.v1.TestService/CreateResource"
	// TestServiceGetResourceByIdProcedure is the fully-qualified name of the TestService's
	// GetResourceById RPC.
	TestServiceGetResourceByIdProcedure = "/test.v1.TestService/GetResourceById"
	// TestServiceHealthCheckProcedure is the fully-qualified name of the TestService's HealthCheck RPC.
	TestServiceHealthCheckProcedure = "/test.v1.TestService/HealthCheck"
)

// TestServiceClient is a client for the test.v1.TestService service.
type TestServiceClient interface {
	GetResource(context.Context, *connect.Request[testproto.GetResourceRequest]) (*connect.Response[testproto.GetResourceResponse], error)
	CreateResource(context.Context, *connect.Request[testproto.CreateResourceRequest]) (*connect.Response[testproto.CreateResourceResponse], error)
	GetResourceById(context.Context, *connect.Request[testproto.GetResourceByIdRequest]) (*connect.Response[testproto.GetResourceResponse], error)
	HealthCheck(context.Context, *connect.Request[testproto.HealthCheckRequest]) (*connect.Response[testproto.HealthCheckResponse], error)
}

// NewTestServiceClient constructs a client for the test.v1.TestService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testServiceMethods := testproto.File_test_service_proto.Services().ByName("TestService").Methods()
	return &testServiceClient{
		getResource: connect.NewClient[testproto.GetResourceRequest, testproto.GetResourceResponse](
			httpClient,
			baseURL+TestServiceGetResourceProcedure,
			connect.WithSchema(testServiceMethods.ByName("GetResource")),
			connect.WithClientOptions(opts...),
		),
		createResource: connect.NewClient[testproto.CreateResourceRequest, testproto.CreateResourceResponse](
			httpClient,
			baseURL+TestServiceCreateResourceProcedure,
			connect.WithSchema(testServiceMethods.ByName("CreateResource")),
			connect.WithClientOptions(opts...),
		),
		getResourceById: connect.NewClient[testproto.GetResourceByIdRequest, testproto.GetResourceResponse](
			httpClient,
			baseURL+TestServiceGetResourceByIdProcedure,
			connect.WithSchema(testServiceMethods.ByName("GetResourceById")),
			connect.WithClientOptions(opts...),
		),
		healthCheck: connect.NewClient[testproto.HealthCheckRequest, testproto.HealthCheckResponse](
			httpClient,
			baseURL+TestServiceHealthCheckProcedure,
			connect.WithSchema(testServiceMethods.ByName("HealthCheck")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testServiceClient implements TestServiceClient.
type testServiceClient struct {
	getResource     *connect.Client[testproto.GetResourceRequest, testproto.GetResourceResponse]
	createResource  *connect.Client[testproto.CreateResourceRequest, testproto.CreateResourceResponse]
	getResourceById *connect.Client[testproto.GetResourceByIdRequest, testproto.GetResourceResponse]
	healthCheck     *connect.Client[testproto.HealthCheckRequest, testproto.HealthCheckResponse]
}

// GetResource calls test.v1.TestService.GetResource.
func (c *testServiceClient) GetResource(ctx context.Context, req *connect.Request[testproto.GetResourceRequest]) (*connect.Response[testproto.GetResourceResponse], error) {
	return c.getResource.CallUnary(ctx, req)
}

// CreateResource calls test.v1.TestService.CreateResource.
func (c *testServiceClient) CreateResource(ctx context.Context, req *connect.Request[testproto.CreateResourceRequest]) (*connect.Response[testproto.CreateResourceResponse], error) {
	return c.createResource.CallUnary(ctx, req)
}

// GetResourceById calls test.v1.TestService.GetResourceById.
func (c *testServiceClient) GetResourceById(ctx context.Context, req *connect.Request[testproto.GetResourceByIdRequest]) (*connect.Response[testproto.GetResourceResponse], error) {
	return c.getResourceById.CallUnary(ctx, req)
}

// HealthCheck calls test.v1.TestService.HealthCheck.
func (c *testServiceClient) HealthCheck(ctx context.Context, req *connect.Request[testproto.HealthCheckRequest]) (*connect.Response[testproto.HealthCheckResponse], error) {
	return c.healthCheck.CallUnary(ctx, req)
}

// TestServiceHandler is an implementation of the test.v1.TestService service.
type TestServiceHandler interface {
	GetResource(context.Context, *connect.Request[testproto.GetResourceRequest]) (*connect.Response[testproto.GetResourceResponse], error)
	CreateResource(context.Context, *connect.Request[testproto.CreateResourceRequest]) (*connect.Response[testproto.CreateResourceResponse], error)
	GetResourceById(context.Context, *connect.Request[testproto.GetResourceByIdRequest]) (*connect.Response[testproto.GetResourceResponse], error)
	HealthCheck(context.Context, *connect.Request[testproto.HealthCheckRequest]) (*connect.Response[testproto.HealthCheckResponse], error)
}

// NewTestServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestServiceHandler(svc TestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testServiceMethods := testproto.File_test_service_proto.Services().ByName("TestService").Methods()
	testServiceGetResourceHandler := connect.NewUnaryHandler(
		TestServiceGetResourceProcedure,
		svc.GetResource,
		connect.WithSchema(testServiceMethods.ByName("GetResource")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceCreateResourceHandler := connect.NewUnaryHandler(
		TestServiceCreateResourceProcedure,
		svc.CreateResource,
		connect.WithSchema(testServiceMethods.ByName("CreateResource")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceGetResourceByIdHandler := connect.NewUnaryHandler(
		TestServiceGetResourceByIdProcedure,
		svc.GetResourceById,
		connect.WithSchema(testServiceMethods.ByName("GetResourceById")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceHealthCheckHandler := connect.NewUnaryHandler(
		TestServiceHealthCheckProcedure,
		svc.HealthCheck,
		connect.WithSchema(testServiceMethods.ByName("HealthCheck")),
		connect.WithHandlerOptions(opts...),
	)
	return "/test.v1.TestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestServiceGetResourceProcedure:
			testServiceGetResourceHandler.ServeHTTP(w, r)
		case TestServiceCreateResourceProcedure:
			testServiceCreateResourceHandler.ServeHTTP(w, r)
		case TestServiceGetResourceByIdProcedure:
			testServiceGetResourceByIdHandler.ServeHTTP(w, r)
		case TestServiceHealthCheckProcedure:
			testServiceHealthCheckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTestServiceHandler struct{}

func (UnimplementedTestServiceHandler) GetResource(context.Context, *connect.Request[testproto.GetResourceRequest]) (*connect.Response[testproto.GetResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("test.v1.TestService.GetResource is not implemented"))
}

func (UnimplementedTestServiceHandler) CreateResource(context.Context, *connect.Request[testproto.CreateResourceRequest]) (*connect.Response[testproto.CreateResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("test.v1.TestService.CreateResource is not implemented"))
}

func (UnimplementedTestServiceHandler) GetResourceById(context.Context, *connect.Request[testproto.GetResourceByIdRequest]) (*connect.Response[testproto.GetResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("test.v1.TestService.GetResourceById is not implemented"))
}

func (UnimplementedTestServiceHandler) HealthCheck(context.Context, *connect.Request[testproto.HealthCheckRequest]) (*connect.Response[testproto.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("test.v1.TestService.HealthCheck is not implemented"))
}
